version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

build_script:
  - cmd: dotnet restore src\Vortice.sln
  - cmd: msbuild /t:Pack /p:Configuration=Release src\Vortice\Vortice.csproj /m

artifacts:
- path: bin\Packages\Release\*.nupkg
  name: Vortice Nugets

deploy:
- provider: NuGet
  server: https://www.myget.org/F/vortice/api/v2/package
  api_key:
    secure: rVfu/HYGH96xeQfy+gRBC/ovHCheQKTjwIeNIE9HlpkN6e4/YtPUqn5f036pSlmi
  skip_symbols: false
  symbol_server: https://www.myget.org/F/vortice/api/v2/package
  artifact: Vortice Nugets
